### ISSUE TITLE
compiling wird nicht fertig durchgeführt

### ISSUE THREAD

**Issue by swinde** [vanilla-thunder/nodejs-less-compiler#2]
Das Script möchte nicht mehr richtig funktionieren! Früher war damit ein sehr schönes arbeiten möglich.
Leider steige ich bei der Fehlermeldung nicht durch.

Hier bleibt das Script hängen. Vielleicht noch wichtig!? Vorher kam die Fehlermeldung aus dem Pull request! Ist vielleicht eine Folge davon?

| type "l" or "less" to compile less files
 | type "map" to toggle sorucemap on and off
 | type "min" to toggle minifying css on and off
min
  > minify set to: true
  > reading source files ...
  > compiling less ...
(node:29765) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ReferenceError: e is not defined

**Comment by vanilla-thunder** [comment]
welche Nodejs Version hast du denn?

**Comment by swinde** [comment]
node v6.11.3
npm 3.10.10

**Comment by vanilla-thunder** [comment]
sowohl node 6.11.0 + npm 5.3.0
als auch node 6.11.3 + npm 3.10.10 funktioniert bei mir nach der Änderung aus dem PR.
Fehlen dir vielleicht die source Dateien von flow? (build Ordner)
Um diese zu bekommen, muss man flow von git holen, im normalen Shop Archiv sind sie nicht dabei.

**Comment by swinde** [comment]
Es handelt sich um OXID 6; 
Im Ordner ../Application/views/flow/build/less/ 
sind 4 Dateien wie immer drin flow.less, responsive.less, theme.less, variablen.less

**Comment by vanilla-thunder** [comment]
jaa dann musst du den Pfad Anpassen 😄 
application => **A**pplication
Zeile 10

**Comment by swinde** [comment]
Das habe ich doch! Geht trotzdem nicht.

**Comment by vanilla-thunder** [comment]
wurde es auch ganz sicher gespeichert? Bei kam auch die "Unhandled promise rejection" Fehlermeldung, aber nach der Anpassung des Pfades gings wieder.
Auf was für einem Betriebssystem hasst du es? Ich habe hier ein Ubuntu 16.04
![image](https://user-images.githubusercontent.com/1874024/35978288-9924d1ee-0ce5-11e8-8512-279fa626e5dc.png)

**Comment by swinde** [comment]
Ich habe jetzt noch einmal den gesamten node_modules Ordner gelöscht und mit npm install nochmal installiert. Jetzt geht es!

Ich glaube ISSUES kann geschlossen werden.
